os: linux
jobs:
  include:
    - stage: "sleep 109"
before_script:
  - travis_key Art cosign.key
keys:
  - Art 
env: 
  secret: "C@S1GN#$&"
script:
  - cosign sign --key cosign.key arthanaharidas/python-hello-world:latest
