os: linux
jobs:
  include:
    - stage: "sleep 109"
env: 
  secret: "C@S1GN#$&"    
before_script:
  - travis_key Key cosign.key
keys:
  - Key
#env: 
 # secret: "C@S1GN#$&"
script:
  - cosign sign --key cosign.key arthanaharidas/python-hello-world:latest
